### ISSUE TITLE
Course notes.md - Recycler.bin

### ISSUE THREAD

**Issue by sten97** [CourseNotesBTH/DV1592#1]
In Windows XP the recycle bin folder were named "Recycler" and INFO2  contains the user's SID for every file in the recycle bin.

In Windows Vista+  the recycle bin folder were named "$Recycle.Bin" uses two files one start with a $R and the other witch $I followed by a random string. 
$R - file contains the actual contents of the recycled file. 
$I - file contains the metadata for that specific file.

Source: https://www.magnetforensics.com/blog/artifact-profile-recycle-bin/

**Comment by AlexGustafsson** [comment]
Would you like to create a pull / merge request?

**Comment by sten97** [comment]
Yes
